added creation date in cookie
nhs-digital-gp-it-futures/buying-catalogue-library pull request #118
Opened 2021-05-21 11:43 UTC by nehajain008

Story AB#7250
Task AB#14642

2021-05-24 20:14 UTC, kiran-mastek submitted a review, later dismissed

2021-05-25 08:19 UTC, bjss-chris approved these changes

2021-05-25 08:21 UTC, bjss-chris requested changes
Just need to update the version number, recommend running `npm version minor --no-git-tag-version`.

2021-05-25 08:41 UTC, nehajain008 commented
> 
> 
> Just need to update the version number, recommend running `npm version minor --no-git-tag-version`.

Updated

2021-05-25 08:43 UTC, bjss-chris approved these changes

2021-05-25 08:44 UTC, NickNewlands approved these changes

2021-05-25 08:53 UTC, merged